/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myDemoApp;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static int mulElements(ArrayList<Integer> list, int index1, int index2){ //multiplies the elements in the list of index1 and index2.
        if(list.isEmpty())
            return -1;
        if(list.size() < index1 || list.size() < index2)
            throw new RuntimeException();
        if(list.get(index1) == 0 || list.get(index2) == 0)
            return 0;

        return list.get(index1) * list.get(index2);
    }

    public static void main(String[] args) {
        System.out.println("selam");
    }
}