/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myDemoApp;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    public void emptyList(){
        ArrayList<Integer> list = new ArrayList<>();
        assertEquals(-1, App.mulElements(list, 2, 3));

    }

    @Test
    public void firstIndexOutOfTheBoundary(){
        ArrayList<Integer> list = new ArrayList<>();
        list.add(1);
        list.add(2);
        list.add(3);
        
        assertThrows(RuntimeException.class, () -> { App.mulElements(list,4,2); });
    }

    @Test
    public void secondIndexOutOfTheBoundary(){
        ArrayList<Integer> list = new ArrayList<>();
        list.add(1);
        list.add(2);
        list.add(3);
        
        assertThrows(RuntimeException.class, () -> { App.mulElements(list,2,4); });
    }

    @Test
    public void firstIndexElementIsZero(){
        ArrayList<Integer> list = new ArrayList<>();
        list.add(1);
        list.add(0);
        list.add(5);

        assertEquals(0, App.mulElements(list, 1, 2));

    }

    @Test
    public void secondIndexElementIsZero(){
        ArrayList<Integer> list = new ArrayList<>();
        list.add(1);
        list.add(3);
        list.add(0);

        assertEquals(0, App.mulElements(list, 1, 2));
        
    }
}

